import { ICommand } from './types';
import {
  FolderTree,
  BookOpen,
  GraduationCap,
  Sidebar,
  PanelRight,
  Play,
  RefreshCw,
  Moon,
  Sun,
  Monitor,
  Trash2,
  Save,
  Cpu,
  Zap,
  CheckCircle,
  Code,
  FileCode,
  Terminal,
  Scale,
  Activity,
  Maximize2,
  MousePointer,
  BoxSelect,
  CircleDot,
  ArrowUpRight,
  FilePlus,
  Layers,
  Search,
  Stethoscope,
  Sparkles,
  Grid,
  Calculator,
  GitBranch,
  AlertTriangle,
  Split,
  Wrench,
  Trophy,
  Bot,
} from 'lucide-react';

export const COMMAND_REGISTRY: ICommand[] = [
  // ---------------------------------------------------------------------------
  // 1. Canvas Commands
  // ---------------------------------------------------------------------------
  {
    id: 'canvas-tool-select',
    title: 'Select Pointer Tool',
    category: 'Canvas',
    icon: MousePointer,
    shortcut: 'V',
    description: 'Switch active tool to pointer selection',
    keywords: ['select', 'pointer', 'cursor', 'tool'],
  },
  {
    id: 'canvas-tool-box',
    title: 'Marquee Box Selection Tool',
    category: 'Canvas',
    icon: BoxSelect,
    shortcut: 'Shift+V',
    description: 'Switch active tool to rectangular box marquee selection',
    keywords: ['box', 'marquee', 'multi-select', 'select'],
  },
  {
    id: 'canvas-tool-state',
    title: 'Place State Node Tool',
    category: 'Canvas',
    icon: CircleDot,
    shortcut: 'S',
    description: 'Switch active tool to state node creation',
    keywords: ['state', 'node', 'vertex', 'create', 'add'],
  },
  {
    id: 'canvas-tool-transition',
    title: 'Draw Transition Edge Tool',
    category: 'Canvas',
    icon: ArrowUpRight,
    shortcut: 'T',
    description: 'Switch active tool to transition edge creation',
    keywords: ['transition', 'edge', 'arrow', 'delta', 'draw', 'create'],
  },
  {
    id: 'canvas-tool-erase',
    title: 'Erase Element Tool',
    category: 'Canvas',
    icon: Trash2,
    shortcut: 'E',
    description: 'Switch active tool to eraser',
    keywords: ['erase', 'delete', 'remove'],
  },
  {
    id: 'canvas-select-all',
    title: 'Select All Elements',
    category: 'Canvas',
    icon: BoxSelect,
    shortcut: 'Ctrl+A',
    description: 'Select all state nodes and transition edges on canvas',
    keywords: ['select all', 'all', 'everything'],
  },
  {
    id: 'canvas-clear-selection',
    title: 'Clear Selection',
    category: 'Canvas',
    icon: MousePointer,
    description: 'Deselect all currently selected nodes and edges',
    keywords: ['deselect', 'clear selection', 'unselect'],
  },
  {
    id: 'canvas-delete-selected',
    title: 'Delete Selected Elements',
    category: 'Canvas',
    icon: Trash2,
    shortcut: 'Delete',
    description: 'Remove all selected states and transitions from canvas',
    keywords: ['delete', 'remove', 'selected', 'backspace'],
  },
  {
    id: 'canvas-focus-toggle',
    title: 'Toggle Canvas Focus Mode',
    category: 'Canvas',
    icon: Maximize2,
    shortcut: 'Ctrl+Shift+F',
    description: 'Maximize canvas area by collapsing sidebars and bottom panels',
    keywords: ['focus', 'fullscreen', 'maximize', 'zen', 'hide panels'],
  },

  // ---------------------------------------------------------------------------
  // 2. Machine Models & Switching
  // ---------------------------------------------------------------------------
  {
    id: 'machine-set-dfa',
    title: 'Switch / Create DFA (Deterministic Finite Automaton)',
    category: 'Machines',
    icon: Cpu,
    description: 'Set workspace model to Deterministic Finite Automaton',
    keywords: ['dfa', 'finite automaton', 'deterministic', 'fa', 'machine'],
  },
  {
    id: 'machine-set-nfa',
    title: 'Switch / Create NFA (Nondeterministic Finite Automaton)',
    category: 'Machines',
    icon: Cpu,
    description: 'Set workspace model to Nondeterministic Finite Automaton',
    keywords: ['nfa', 'nondeterministic', 'fa', 'machine'],
  },
  {
    id: 'machine-set-pda',
    title: 'Switch / Create PDA (Pushdown Automaton)',
    category: 'Machines',
    icon: Layers,
    description: 'Set workspace model to Pushdown Automaton with stack memory',
    keywords: ['pda', 'pushdown', 'stack', 'automaton', 'context-free'],
  },
  {
    id: 'machine-set-tm',
    title: 'Switch / Create Turing Machine',
    category: 'Machines',
    icon: Terminal,
    description: 'Set workspace model to Turing Machine with tape execution',
    keywords: ['tm', 'turing', 'tape', 'machine', 'computability'],
  },
  {
    id: 'machine-undo',
    title: 'Undo Canvas Mutation',
    category: 'Workspace',
    icon: RefreshCw,
    shortcut: 'Ctrl+Z',
    description: 'Revert last canvas modification',
    keywords: ['undo', 'history', 'revert'],
  },
  {
    id: 'machine-redo',
    title: 'Redo Canvas Mutation',
    category: 'Workspace',
    icon: RefreshCw,
    shortcut: 'Ctrl+Shift+Z',
    description: 'Reapply undone canvas modification',
    keywords: ['redo', 'history', 'reapply'],
  },
  {
    id: 'machine-clear',
    title: 'New / Clear Automaton Machine',
    category: 'Workspace',
    icon: FilePlus,
    description: 'Clear all states and transitions to start a fresh machine',
    keywords: ['clear', 'reset', 'delete', 'new', 'blank'],
  },
  {
    id: 'machine-save',
    title: 'Save Active Automaton Machine File',
    category: 'Workspace',
    icon: Save,
    shortcut: 'Ctrl+S',
    description: 'Export and download current machine specification (.projectzero)',
    keywords: ['save', 'serialize', 'export', 'download', 'file'],
  },

  // ---------------------------------------------------------------------------
  // 3. Navigation & Workbench Panels
  // ---------------------------------------------------------------------------
  {
    id: 'nav-trace',
    title: 'Open Execution Trace View',
    category: 'Navigation',
    icon: Play,
    shortcut: 'Ctrl+1',
    description: 'Open step-by-step simulator execution trace in bottom panel',
    keywords: ['trace', 'execution', 'simulate', 'run', 'step', 'debug'],
  },
  {
    id: 'nav-pda-branch',
    title: 'Open PDA Branch Tree View',
    category: 'Navigation',
    icon: GitBranch,
    shortcut: 'Ctrl+2',
    description: 'Open nondeterministic PDA computation tree visualizer',
    keywords: ['pda', 'branch', 'tree', 'nondeterminism', 'paths'],
  },
  {
    id: 'nav-batch-tester',
    title: 'Open Batch String Tester',
    category: 'Navigation',
    icon: Layers,
    shortcut: 'Ctrl+3',
    description: 'Test multiple input strings simultaneously against active automaton',
    keywords: ['tester', 'batch', 'strings', 'test', 'accept', 'reject'],
  },
  {
    id: 'nav-console-logs',
    title: 'Open Console Telemetry Logs',
    category: 'Navigation',
    icon: Terminal,
    shortcut: 'Ctrl+4',
    description: 'View solver logs, computation diagnostics, and events',
    keywords: ['logs', 'console', 'events', 'telemetry'],
  },
  {
    id: 'nav-diagnostics',
    title: 'Open Diagnostics & Health Panel',
    category: 'Navigation',
    icon: Stethoscope,
    shortcut: 'Ctrl+5',
    description: 'View unreachable states, dead ends, and formal validation warnings',
    keywords: ['diagnostics', 'health', 'validation', 'unreachable', 'dead end'],
  },
  {
    id: 'nav-equivalence-repair',
    title: 'Open Equivalence & Repair Panel',
    category: 'Navigation',
    icon: Search,
    shortcut: 'Ctrl+6',
    description: 'Compare language equivalence and execute guided repair algorithms',
    keywords: ['equivalence', 'repair', 'compare', 'guided repair', 'bisimulation'],
  },
  {
    id: 'nav-matrix',
    title: 'Open Transition Matrix / Table',
    category: 'Navigation',
    icon: Grid,
    shortcut: 'Ctrl+7',
    description: 'View formal state transition matrix tabular representation',
    keywords: ['matrix', 'table', 'transition matrix', 'grid'],
  },
  {
    id: 'nav-formal-math',
    title: 'Open Formal Math Specification',
    category: 'Navigation',
    icon: Calculator,
    shortcut: 'Ctrl+8',
    description: 'View 5-tuple / 7-tuple mathematical specification: Q, Σ, δ, q0, F',
    keywords: ['math', 'formal', 'specification', 'tuple', 'definition'],
  },
  {
    id: 'nav-algorithm-visualizer',
    title: 'Open Algorithm Step Visualizer',
    category: 'Navigation',
    icon: Cpu,
    shortcut: 'Ctrl+9',
    description: 'View step-by-step algorithms: Subset Construction, Minimization, etc.',
    keywords: ['algorithm', 'steps', 'visualizer', 'subset', 'hopcroft'],
  },
  {
    id: 'nav-challenges',
    title: 'Open Automata Challenges & Problem Sets',
    category: 'Navigation',
    icon: Trophy,
    shortcut: 'Ctrl+Shift+C',
    description: 'Solve interactive automata design challenges and quizzes',
    keywords: ['challenges', 'problems', 'quizzes', 'tests', 'exercises'],
  },

  // ---------------------------------------------------------------------------
  // 4. Grammar Workbench Subviews
  // ---------------------------------------------------------------------------
  {
    id: 'grammar-open-workbench',
    title: 'Open Context-Free Grammar (CFG) Workbench',
    category: 'Grammar',
    icon: BookOpen,
    shortcut: 'Ctrl+0',
    description: 'Open full Context-Free Grammar analysis and parser studio',
    keywords: ['grammar', 'cfg', 'workbench', 'context-free', 'bnf'],
  },
  {
    id: 'grammar-editor',
    title: 'Grammar: Open Grammar Editor',
    category: 'Grammar',
    icon: FileCode,
    description: 'Edit CFG production rules in visual or BNF text mode',
    keywords: ['grammar', 'editor', 'productions', 'bnf', 'rules'],
  },
  {
    id: 'grammar-validate',
    title: 'Grammar: Validate Grammar Rules',
    category: 'Grammar',
    icon: CheckCircle,
    description: 'Verify CFG variables, terminals, reachability, and productivity',
    keywords: ['grammar', 'validate', 'verification', 'productive', 'reachable'],
  },
  {
    id: 'grammar-analysis',
    title: 'Grammar: Structural Analysis',
    category: 'Grammar',
    icon: Search,
    description: 'Analyze language nullability, unit productions, and cycles',
    keywords: ['grammar', 'analysis', 'nullable', 'unit', 'cycles'],
  },
  {
    id: 'grammar-derivation',
    title: 'Grammar: Step-by-Step Derivation & Parse Tree',
    category: 'Grammar',
    icon: GitBranch,
    description: 'Generate leftmost/rightmost derivation sequence and syntax tree',
    keywords: ['grammar', 'derivation', 'parse tree', 'syntax tree', 'leftmost'],
  },
  {
    id: 'grammar-membership',
    title: 'Grammar: CF Language Membership L(G)',
    category: 'Grammar',
    icon: Layers,
    description: 'Test string membership and sample language generated by CFG',
    keywords: ['grammar', 'membership', 'language', 'sample', 'l(g)'],
  },
  {
    id: 'grammar-ambiguity',
    title: 'Grammar: Ambiguity Detection Studio',
    category: 'Grammar',
    icon: AlertTriangle,
    description: 'Detect ambiguous grammars by finding dual parse trees',
    keywords: ['grammar', 'ambiguity', 'ambiguous', 'trees', 'precedence'],
  },
  {
    id: 'grammar-first-follow',
    title: 'Grammar: FIRST / FOLLOW Set Computation',
    category: 'Grammar',
    icon: Activity,
    description: 'Compute FIRST and FOLLOW sets with iterative derivation steps',
    keywords: ['grammar', 'first', 'follow', 'sets', 'll1', 'parsing'],
  },
  {
    id: 'grammar-left-recursion',
    title: 'Grammar: Eliminate Left Recursion',
    category: 'Grammar',
    icon: RefreshCw,
    description: 'Detect and eliminate immediate and indirect left recursion',
    keywords: ['grammar', 'left recursion', 'recursion', 'eliminate', 'transform'],
  },
  {
    id: 'grammar-left-factoring',
    title: 'Grammar: Apply Left Factoring',
    category: 'Grammar',
    icon: Split,
    description: 'Left-factor common prefixes for predictive parser construction',
    keywords: ['grammar', 'left factoring', 'factoring', 'prefix', 'transform'],
  },
  {
    id: 'grammar-cnf',
    title: 'Grammar: Chomsky Normal Form (CNF) Transform',
    category: 'Grammar',
    icon: Sparkles,
    description: 'Transform CFG into CNF (A → BC or A → a)',
    keywords: ['grammar', 'cnf', 'chomsky', 'normal form', 'transform'],
  },
  {
    id: 'grammar-gnf',
    title: 'Grammar: Greibach Normal Form (GNF) Transform',
    category: 'Grammar',
    icon: Sparkles,
    description: 'Transform CFG into Greibach Normal Form (A → aα)',
    keywords: ['grammar', 'gnf', 'greibach', 'normal form', 'transform'],
  },
  {
    id: 'grammar-cyk',
    title: 'Grammar: Interactive CYK Chart Parser',
    category: 'Grammar',
    icon: Grid,
    description: 'Run dynamic programming Cocke-Younger-Kasami membership algorithm',
    keywords: ['grammar', 'cyk', 'parser', 'chart', 'cocke younger kasami', 'dp'],
  },
  {
    id: 'grammar-ll1-table',
    title: 'Grammar: Construct LL(1) Parsing Table',
    category: 'Grammar',
    icon: TableIcon(),
    description: 'Build predictive LL(1) M[A, a] dispatch table',
    keywords: ['grammar', 'll1', 'table', 'predictive', 'll(1)', 'parser'],
  },
  {
    id: 'grammar-slr-parser',
    title: 'Grammar: SLR(1) Table & Shift-Reduce Parser',
    category: 'Grammar',
    icon: Cpu,
    description: 'Construct LR(0) collection and execute SLR shift-reduce parsing',
    keywords: ['grammar', 'slr', 'slr1', 'shift reduce', 'lr0', 'bottom up'],
  },
  {
    id: 'grammar-pda-translate',
    title: 'Grammar: PDA ↔ CFG Equivalence Translator',
    category: 'Grammar',
    icon: Scale,
    description: 'Convert Context-Free Grammar to Pushdown Automaton and vice-versa',
    keywords: ['grammar', 'pda', 'translate', 'convert', 'cfg to pda', 'equivalence'],
  },
  {
    id: 'grammar-syntactic-pda',
    title: 'Grammar: Syntactic Statement Interpreter (PDA)',
    category: 'Grammar',
    icon: Terminal,
    description: 'Simulate PDA execution for parsing programming language constructs',
    keywords: ['grammar', 'syntactic', 'pda', 'interpreter', 'statements'],
  },

  // ---------------------------------------------------------------------------
  // 5. Language Theory
  // ---------------------------------------------------------------------------
  {
    id: 'lang-regular-languages',
    title: 'Open Regular Languages & Closure Studio',
    category: 'Languages',
    icon: BookOpen,
    shortcut: 'Ctrl+Shift+R',
    description: 'Explore regular language closure properties: union, intersection, complement',
    keywords: ['regular languages', 'closure', 'union', 'intersection', 'complement'],
  },
  {
    id: 'lang-pumping-lemma',
    title: 'Open Pumping Lemma Proof Assistant',
    category: 'Languages',
    icon: Activity,
    shortcut: 'Ctrl+Shift+U',
    description: 'Interactive adversary game proving non-regularity via Pumping Lemma',
    keywords: ['pumping lemma', 'proof', 'non-regular', 'adversary', 'witness'],
  },
  {
    id: 'lang-fa-regex-equiv',
    title: 'Open FA ↔ RegEx Equivalence Studio',
    category: 'Languages',
    icon: Scale,
    shortcut: 'Ctrl+Shift+E',
    description: 'State elimination (GNFA) and Thompson construction bidirectional studio',
    keywords: ['regex', 'gnfa', 'thompson', 'equivalence', 'state elimination'],
  },
  {
    id: 'lang-program-constructs',
    title: 'Open Program Constructs & Lexical Tokens Library',
    category: 'Languages',
    icon: FileCode,
    shortcut: 'Ctrl+Shift+P',
    description: 'Prebuilt automata for C/Python identifiers, numbers, strings, and comments',
    keywords: ['program constructs', 'tokens', 'c', 'python', 'identifiers', 'literals'],
  },
  {
    id: 'lang-lexical-analyzer',
    title: 'Open Lexical Analyzer & Token Stream Scanner',
    category: 'Languages',
    icon: Code,
    shortcut: 'Ctrl+Shift+L',
    description: 'Simulate DFA-based lexical tokenizer generating token stream from source text',
    keywords: ['lexical analyzer', 'lexer', 'tokenizer', 'scanner', 'tokens'],
  },

  // ---------------------------------------------------------------------------
  // 6. Computability Theory
  // ---------------------------------------------------------------------------
  {
    id: 'comp-church-turing',
    title: 'Open Church–Turing Thesis & Models Studio',
    category: 'Computability',
    icon: Scale,
    description: 'Explore equivalence of Turing Machines, Lambda Calculus, and Post Machines',
    keywords: ['church turing', 'turing machine', 'lambda calculus', 'computability'],
  },
  {
    id: 'comp-re-languages',
    title: 'Open Decidable & RE Languages Hierarchy',
    category: 'Computability',
    icon: GitBranch,
    description: 'Chomsky hierarchy relationships: Regular ⊂ CFL ⊂ Decidable ⊂ RE',
    keywords: ['re languages', 'decidable', 'recursively enumerable', 'hierarchy'],
  },
  {
    id: 'comp-reducibility',
    title: 'Open Mapping Reducibility Studio (A ≤m B)',
    category: 'Computability',
    icon: Zap,
    description: 'Mapping reductions proving undecidability across computational problems',
    keywords: ['reducibility', 'mapping reduction', 'reduction', 'undecidable'],
  },
  {
    id: 'comp-halting-problem',
    title: 'Open Halting Problem & Diagonalization Proof',
    category: 'Computability',
    icon: AlertTriangle,
    description: 'Interactive Cantor diagonalization proof of ATM undecidability',
    keywords: ['halting problem', 'diagonalization', 'atm', 'undecidable', 'turing'],
  },
  {
    id: 'comp-pcp',
    title: 'Open Post Correspondence Problem (PCP) Solver',
    category: 'Computability',
    icon: Split,
    description: 'Interactive domino matching tiles demonstrating undecidable PCP solutions',
    keywords: ['pcp', 'post correspondence', 'domino', 'tiles', 'undecidable'],
  },

  // ---------------------------------------------------------------------------
  // 7. Interoperability & Tools
  // ---------------------------------------------------------------------------
  {
    id: 'tools-interop',
    title: 'Open Interoperability Tools (JFLAP / LEX / YACC)',
    category: 'Tools',
    icon: Wrench,
    description: 'Import/export JFLAP .jff XML and generate C LEX/YACC scanner specifications',
    keywords: ['tools', 'jflap', 'lex', 'yacc', 'import', 'export', 'xml', 'c code'],
  },

  // ---------------------------------------------------------------------------
  // 8. Navigation & UI Layout
  // ---------------------------------------------------------------------------
  {
    id: 'nav-explorer',
    title: 'Focus Project Explorer Panel',
    category: 'Navigation',
    icon: FolderTree,
    shortcut: 'Alt+1',
    description: 'Focus left sidebar file tree and machine hierarchy',
    keywords: ['explorer', 'files', 'tree', 'project'],
  },
  {
    id: 'nav-syllabus',
    title: 'Focus Syllabus Topics Panel',
    category: 'Navigation',
    icon: BookOpen,
    shortcut: 'Alt+2',
    description: 'Focus curriculum modules and theoretical topics',
    keywords: ['syllabus', 'modules', 'course', 'learn'],
  },
  {
    id: 'nav-quizzes',
    title: 'Focus Quiz Challenges Panel',
    category: 'Navigation',
    icon: GraduationCap,
    shortcut: 'Alt+3',
    description: 'Focus interactive quizzes and comprehension checks',
    keywords: ['quizzes', 'tests', 'challenges'],
  },
  {
    id: 'view-toggle-sidebar',
    title: 'Toggle Left Navigation Sidebar',
    category: 'Workspace',
    icon: Sidebar,
    shortcut: 'Ctrl+B',
    description: 'Show or collapse the left explorer sidebar',
    keywords: ['sidebar', 'left', 'hide', 'show'],
  },
  {
    id: 'view-toggle-inspector',
    title: 'Toggle Right Property Inspector',
    category: 'Workspace',
    icon: PanelRight,
    shortcut: 'Ctrl+Shift+P',
    description: 'Show or collapse the right property inspector panel',
    keywords: ['inspector', 'properties', 'right', 'hide', 'show'],
  },
  {
    id: 'view-toggle-bottom',
    title: 'Toggle Bottom Telemetry Panel',
    category: 'Workspace',
    icon: Play,
    shortcut: 'Ctrl+J',
    description: 'Show or collapse the bottom analysis panel',
    keywords: ['bottom', 'trace', 'matrix', 'logs', 'panel'],
  },
  {
    id: 'view-reset-layout',
    title: 'Reset Workspace Layout Ratios',
    category: 'Workspace',
    icon: RefreshCw,
    description: 'Restore default sidebar, inspector, and bottom panel dimensions',
    keywords: ['reset', 'layout', 'default', 'restore'],
  },
  {
    id: 'ai-open-assistant',
    title: 'Open Theoretical AI Assistant Workspace',
    category: 'Workspace',
    icon: Bot,
    description: 'Open dedicated AI Assistant workspace surface in right panel',
    keywords: ['ai', 'assistant', 'tutor', 'guidance', 'chat', 'proofs'],
  },

  // ---------------------------------------------------------------------------
  // 9. Themes
  // ---------------------------------------------------------------------------
  {
    id: 'theme-dark',
    title: 'Switch to Dark Theme',
    category: 'Theme',
    icon: Moon,
    description: 'Set modern dark IDE aesthetic with high-contrast borders',
    keywords: ['theme', 'dark', 'mode', 'night'],
  },
  {
    id: 'theme-light',
    title: 'Switch to Light Theme',
    category: 'Theme',
    icon: Sun,
    description: 'Set light paper workspace color scheme',
    keywords: ['theme', 'light', 'mode', 'day'],
  },
  {
    id: 'theme-contrast',
    title: 'Switch to High Contrast Theme',
    category: 'Theme',
    icon: Monitor,
    description: 'Set accessible maximum contrast color palette',
    keywords: ['theme', 'contrast', 'high', 'accessibility'],
  },
];

function TableIcon() {
  return Grid;
}
